accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('acc', views.account, name="acc"),
    path('login', views.log_in, name="login"),
    path('logout', views.log_out, name='logout')
]

applab8/urls.py
from django.urls import path
from . import views

app_name = 'appLab8'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('', views.redirecting, name='redirecting'),
    # dilanjutkan ...
]

prolab8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applab8.urls')),
    path('accounts/', include('accounts.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

applab8/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def account(req):
    error = "Username atau Password anda salah"
    user = req.user
    if user.is_authenticated:
        return redirect('accounts:login')
    if req.method == 'POST':
        form = AuthenticationForm(data=req.POST)
        if form.is_valid():
            user = form.get_user()
            login(req, user)
            return redirect('accounts:login')
    else:
        form = AuthenticationForm()
    return render(req, 'account.html', {'form':form, 'error':error})

def log_in(req):
    return render(req, 'login.html')

def log_out(req):
    logout(req)
    return redirect('accounts:acc')

applab8/views.py
from django.shortcuts import render, redirect

# Create your views here.
def index(request):
    return render(request, 'index.html')

def redirecting(request):
    return redirect('/index/')

accounts/templates/account.html
{% load static %}
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <title>kinda Book Finder</title>
        <style>
          body {
              background-color: #F8FAD7;
              background-position: center;
              height: 100%;
              background-repeat: no-repeat;
              background-size: cover;
          }

          h2,
          h1 {
              font-family: 'Righteous', sans-serif;
              background-color: #FAEBD7;
          }
        </style>
</head>

{% block content %}
<div class="text-center" style="margin-top: 30px;">
    <h1>Hello world!</h1>
    <h2>Log in</h2>
    {% if form.errors %}
    {{error}}
    {% endif %}
    <form method="POST" action='{% url "accounts:acc" %}'>
        {% csrf_token %}
        <label>Username</label>
        <br>
        {{ form.username }}
        <br>
        <label>Password</label>
        <br>
        {{ form.password }}
        <br>
        <input type="submit" value="Log in" class="button">
    </form>
</div>
<link rel="stylesheet" href="{% static 'css/account.css'%}">
{% endblock %}

accounts/templates/login.html
{% load static %}

{% load static %}
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <title>kinda Book Finder</title>
        <style>
        body {
            background-color: #F8FAD7;
            background-position: center;
            height: 100%;
            background-repeat: no-repeat;
            background-size: cover;
        }

        h2,
        h1 {
            font-family: 'Righteous', sans-serif;
            background-color: #FAEBD7;
        }
        </style>
</head>

{% block content %}

<div class="text-center" style="margin-top: 30px;">
    {% if user.is_authenticated %}
    <h1>Selamat datang, {{user}}</h1>
    <a href="{% url 'accounts:logout' %}">
        <div class='logout'>
            Log out
        </div>
    </a>
    {% else %}
    <h1>Log in dulu ya!</h1>
    <a href="{% url 'accounts:acc' %}">
        <div class='login'>
            Log in
        </div>
    </a>
    {% endif %}

</div>
<link rel="stylesheet" href="{% static 'css/account.css'%}">
{% endblock %}

applab8/templates/index.html
<!DOCTYPE html> {% load static %}
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>kinda Book Finder</title>
</head>
<body>
    <div class="container">
        <h1 id="title" class="text-center mt-5">Book Finder</h1>
        <div class="row">
            <div id="input" class="input-group mx-auto col-lg-6 col-md-8 col-sm-12">
                <input id="search-box" type="text" class="form-control" placeholder="Search Books..." value="">
                <button id="search" class="btn btn-primary" onclick="">Search</button>
            </div>
        </div>
        <div class="book-list">
            <h2 class="text-center">Search result</h2>
            <div id="list-output" class="">
                <div class="row">

                </div>
            </div>
        </div>
    </div>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.js"></script>
    <link rel="stylesheet" href="{% static 'css/mystyle.css'%}">
    <script type="text/javascript" src="{% static 'js/myscript.js'%}"></script>
</body>

</html>